const ImageKit= require("imagekit");

const imagekit = new ImageKit({
    publicKey: process.env.IMAGEKIT_PUBLIC_KEY,
    privateKey: process.env.IMAGEKIT_PRIVATE_KEY,
    urlEndpoint: process.env.IMAGEKIT_URL_ENDPOINT
});

async function uploadFile(file,fileName){
    const result=await ImageKit.upload({
        file:file, //required
        fileName:fileName, //required and will be generated by the uuid
        folder:"/food-view" //creates a new folder for storing the content for the specific application 
    })

    return result; //result.url will the thing which we will store in the db for the retrivel of the file
}

module.exports={
    uploadFile
}