const ImageKit= require("imagekit");

async function uploadFile(file,fileName){
    const result=await ImageKit.uplaod({
        file:file, //required
        fileName:fileName, //required and will be generated by the uuid
    })

    return result; //result.url will the thing which we will store in the db for the retrivel of the file
}

module.exports={
    uploadFile
}